Add:サークル名変更エンドポイントの追加
lc-tut/club-portal pull request #62
Opened 2024-11-01 09:55 UTC by Mikuto0831

Club名を変更するエンドポイント`/name`をPUTで追加しました

テスト方法がいまいちつかめず、ローカル環境ではほとんどのエンドポイントから307が返ってきたため、正常な動作ができるかわかりません....

2024-11-04 06:43 UTC, KashEight commented on repos/clubs/repo.go
> +	ClubNameRepo
repository が追加されているのはよさそう 👍

2024-11-04 06:46 UTC, KashEight commented on repos/clubs/name_test.go
test が落ちるのはどうしようもなさそう (完全に用意してなかったのもあるので…)

2024-11-04 07:04 UTC, KashEight commented
レビューコメント追加しました
あとは、`openapi.yaml` のエンドポイントを追加してくれればよさそうな気がします

2024-11-08 09:57 UTC, KashEight requested changes

2024-11-08 09:57 UTC, KashEight commented on router/v1/name.go
> +		pd := &ClubCreatePostData{}
`ClubNamePostData` という専用の struct 作ってやった方が効率的かな…？
(例に書いてあるやつ、定義してあるけど使ってないのは完全にミスです…)

例: https://github.com/lc-tut/club-portal/blob/512a02736507f86cbb6bfeb429598f881dcf1f95/router/v1/description.go#L27-L29

2024-11-08 09:57 UTC, KashEight commented on repos/clubs/page.go
> +	Name            string
ここの `ClubPageUpdateArgs` はトランザクションありの Update なので、入れる場合は `repos/clubs/name.go` にトランザクション用のメソッド生やした方がいい気がします！

例: https://github.com/lc-tut/club-portal/blob/512a02736507f86cbb6bfeb429598f881dcf1f95/repos/clubs/achievement.go#L77

2024-11-08 09:58 UTC, KashEight commented
Pending のままだった…ずっと気づかなくなって申し訳ないです🙏

2024-11-18 03:39 UTC, Mikuto0831 commented
長く間が空いてしまいましたが再びreviewしていただけると幸いです！

2024-11-18 03:58 UTC, Mikuto0831 commented
間がかなり空いてしまいましたが再びレビューしていただけると幸いです！

2024-11-18 10:34 UTC, KashEight approved these changes

2024-11-18 10:35 UTC, KashEight commented
LGTM！よさそう！

2024-11-21 02:39 UTC, merged